import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <Providers>
        <MantineProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <body className={inter.className}>{children}</body>
          </HydrationBoundary>
        </MantineProvider>
      </Providers>
    </html>
  );
}
